feat(cli): ui eslint result component
atls/tools pull request #296
Opened 2024-02-09 12:24 UTC by TorinAsakura

2024-03-07 06:16 UTC, Nelfimov requested changes
на доработку

2024-04-03 16:25 UTC, Nelfimov commented
## Текущий статус

- билд перенесен на 4.1.1
- билд бандла стабилизирован, большая часть ворнингов зависимостей исправлена

## Блокирующие элементы

Запуск скриптов
- `yarn check`
  - `format`
  - `lint`
  - `typecheck`
- `yarn test ...`

Заканчивается ошибкой зависимостей

<details>

<summary>yarn format</summary>

```
nikoroach@Nikitas-MacBook-Pro tools % yarn format
➤ YN0000: ┌ Format
➤ YN0000: │ No parser could be inferred for file "package.json".
```

</details>

<details>

<summary>yarn lint</summary>

```
nikoroach@Nikitas-MacBook-Pro tools % yarn lint
➤ YN0000: ┌ Lint
➤ YN0000: │ Cannot find package 'eslint' imported from /Users/nikoroach/Documents/Typescript/atlantis/tools/.yarn/dist/worker.mjs
```

</details>

<details>

<summary>yarn typecheck</summary>

```
nikoroach@Nikitas-MacBook-Pro tools % yarn typecheck
➤ YN0000: ┌ Typecheck
➤ YN0000: │ Cannot find package 'typescript' imported from /Users/nikoroach/Documents/Typescript/atlantis/tools/.yarn/dist/worker.mjs
```

</details>

<details>

<summary>yarn test</summary>

```
nikoroach@Nikitas-MacBook-Pro tools % yarn test unit
➤ YN0001: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@jest/core' imported from /Users/nikoroach/Documents/Typescript/atlantis/tools/.yarn/dist/worker.mjs
```

</details>

@TorinAsakura прошу помощи.

2024-04-05 07:48 UTC, Nelfimov commented
## Апдейт

изменение версии `typescript` не влияет на ошибку. Испробованы
- 4.8
- 4.9
- 5.0
- 5.1
- 5.4

Порядок воспроизведения:
1. через резолюшены зафиксировать версию ts
2. сбилдить новый бандл
3. использовать новый бандл для запуска скриптов

2024-04-05 10:35 UTC, TorinAsakura commented
> nikoroach@Nikitas-MacBook-Pro tools % yarn format
> ➤ YN0000: ┌ Format
> ➤ YN0000: │ No parser could be inferred for file "package.json".

https://stackoverflow.com/questions/50555943/running-into-couldnt-infer-parser-error-using-vue-cli

2024-04-05 10:37 UTC, TorinAsakura commented
> ## Текущий статус
> * билд перенесен на 4.1.1
> * билд бандла стабилизирован, большая часть ворнингов зависимостей исправлена
> 
> ## Блокирующие элементы
> Запуск скриптов
> 
> * `yarn check`
>   
>   * `format`
>   * `lint`
>   * `typecheck`
> * `yarn test ...`
> 
> Заканчивается ошибкой зависимостей
> 
> yarn format
> ```
> nikoroach@Nikitas-MacBook-Pro tools % yarn format
> ➤ YN0000: ┌ Format
> ➤ YN0000: │ No parser could be inferred for file "package.json".
> ```

Посмотри наш пекедж, мы используем директиву экспорт в которой указываем жсон, а он пока в это гавно не умеет, проверь этот момент

2024-06-06 21:18 UTC, TorinAsakura commented
так это, чо готово-то? А что с конфликтами-то?

2024-06-07 06:19 UTC, Nelfimov commented
> так это, чо готово-то? А что с конфликтами-то?

Конфликты порезолвил.

Ошибки `yarn check` по прежнему остаются. Так же у `yarn test ...`

2024-06-25 08:17 UTC, merged